.github/ISSUE_TEMPLATE.md, .tx/config, Makefile, README.rst, bulk_grades/api.py, bulk_grades/apps.py, bulk_grades/urls.py, bulk_grades/views.py, docs/Makefile, docs/conf.py, docs/index.rst, docs/make.bat, docs/testing.rst, openedx.yaml, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, setup.py, tests/test_api.py, tests/test_models.py
This adds an endpoint at `/api/bulk_grades/{course_id}` for exporting and importing a CSV of subsection grades.
=> Added grade export API

bulk_grades/api.py, bulk_grades/views.py, mock_apps/lms/djangoapps/grades/api.py, mock_apps/student/models.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, test_settings.py, tests/test_api.py, tests/test_models.py
* Improve tests and move super_csv dependency to edx
* Added the ability to retrieve a CSV of the errors. Request `/api/bulk_grades/{course_id}/?error_id={error_id}` -- error_id is returned from the original import request.
=> Improved error handling

bulk_grades/__init__.py, bulk_grades/api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Float, not Int

bulk_grades/api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Validation error message was not being reported correctly

bulk_grades/__init__.py, bulk_grades/api.py
Checksum quoting and excel transformation issues were making this feature unreliable. For now, let's turn off checksumming and see whether it's necessary.
=> Remove checksum column from SGP

bulk_grades/urls.py, bulk_grades/views.py
Beginning work for the interventions pipeline. Created an initial refactoring to move common functionality into a mixin.
=> EDUCATOR-4532 new endpoint and initial refactor

bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
* Add cohort name to CSV export
* Change who_last_graded to username instead of user id
* Validate that points are greater than 0
* Rename last_points to Previous Points and points to New Points, for better legibility
=> SGP Improvements

bulk_grades/__init__.py, bulk_grades/api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Renamed key

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/views.py, mock_apps/lms/djangoapps/grades/api.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, tests/test_api.py
**Description:** Add ability to filter by course grade, provided as a percentage to the endpoint.
**JIRA:** https://openedx.atlassian.net/browse/EDUCATOR-4432
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
- @matthugs 
finished.
=> add course level grade filters to CSV export

bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/apps.py, bulk_grades/clients.py, bulk_grades/settings/common.py, bulk_grades/settings/production.py, bulk_grades/settings/test.py, bulk_grades/views.py, mock_apps/lms/djangoapps/grades/api.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, test_settings.py, tests/test_api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> EDUCATOR-4407 call into analytics and create intervention csv

bulk_grades/__init__.py, bulk_grades/api.py
For [EDUCATOR-4528](https://openedx.atlassian.net/browse/EDUCATOR-4528)
=> Always save the input file data, so that error exports work correctly

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/views.py
- Add subsection & grading type filters
- add assignment grade filters
- add the course filters as well
**JIRA:** https://openedx.atlassian.net/browse/EDUCATOR-4537
**Reviewers:**
finished.
**Author concerns:** Duplicated code - but not more than a second place. (If three is the threshold then this is the appropriate level of messiness.)
=> Add filters to the interventions CSV report

bulk_grades/settings/production.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> update production url for intervention

bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/clients.py, bulk_grades/settings/local.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> update url and add logging

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> display grade override as grade if it exists

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
**Description:** Prevent user from setting a negative grade.
**JIRA:** [EDUCATOR-4617](https://openedx.atlassian.net/browse/EDUCATOR-4617)
**Reviewers:**
@matthugs 
@Andytr1
`@iloveagent57` 
finished.
=> scores must be positive

bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> EDUCATOR-4611 rename columns

README.rst
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> EDUCATOR-4408 bulk grades docs

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py
https://openedx.atlassian.net/browse/EDUCATOR-4638
finished.
=> 0.6.4 | GradeCSVProcessor.save() should return something.

openedx.yaml
**Description:** Updates openedx.yaml to current owner and supporting team
**JIRA:** [EDUCATOR-4739](https://openedx.atlassian.net/browse/EDUCATOR-4739)
finished.
=> change owner and supporting team

bulk_grades/api.py, bulk_grades/models.py, pylintrc, pylintrc_tweaks, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.in, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, tox.ini
**Issue:** [BOM-1658](https://openedx.atlassian.net/browse/BOM-1658)
- Removed `caniusepython3` package.
=> Removing caniusepython3 package

bulk_grades/__init__.py
py3.8 supported release.
Bump the version.
finished.
=> py3.8 supported release

requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1932
=> BOM-1932 : Django30 deprecation warnings fix

bulk_grades/api.py, tests/test_api.py, tests/test_models.py, tests/test_views.py
Fix import order using isort to help requirement upgrade to pass quality.
=> Update the sorting so the PR passes quality check

bulk_grades/__init__.py, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pii_check.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
**Description:** Fix for failed upgrade job: pins jinja2, MarkupSafe, and click to avoid version conflicts.
finished.
=> Python Requirements Update

.github/workflows/upgrade-python-requirements.yml, bulk_grades/__init__.py
**Description:** Update python upgrade job email to Aurora
**JIRA:** https://2u-internal.atlassian.net/browse/AU-778
finished.~ (N/A)
=> feat: upgrade python requirements email

.github/workflows/ci.yml, requirements/ci.in, requirements/ci.txt, requirements/dev.txt, tox.ini
, and also configure coverage reports being generated
Context: https://about.codecov.io/blog/message-regarding-the-pypi-package/
=> build: remove unnecessary codecov dependency, upgrade GHA
