CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/urls.py, bulk_grades/views.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, tests/test_api.py, tox.ini
**Description:** Fixes bug
**JIRA:** Fixes are blocking for EDUCATOR-4367 
**Dependencies:** https://github.com/edx/super-csv/pull/6
Now that gradebook has import functionality, we can test there
1. Create a course with graded subsection(s) & add a masters track to it (http://localhost:18000/admin/course_modes/coursemode/)
2. enroll some learner in the course
3. View gradebook page for that course (http://localhost:1994/<your_course_key>) and switch to bulk management tab
4. Export grade CSV
5. Change a grade in the csv
6. Import the csv
**Reviewers:**
finished.
=> WIP: fix mismatch between interface and call site

bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/views.py, mock_apps/lms/djangoapps/grades/api.py, tests/test_api.py
The "grade" in the courseware studentmodule table should not actually be a calculated grade, since the grading library expects to calculate each point in order to roll it into the subsection grade. 
[EDUCATOR-4549](https://openedx.atlassian.net/browse/EDUCATOR-4549)
=> The grade in CSM should be the raw score, not a computed grade

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, mock_apps/lms/djangoapps/grades/api.py
**Description:** Previously CSV was writing/reading the _all grade fields, where we
should've been using exclusively the _graded fields as that's what
preexisting gradebook functionality writes/reads.
**Reviewers:**
finished.
**Author concerns:** This sort of change isn't super helpful without having clarity among members of the team about the semantics of the fields & why the `_graded` ones are more correct. I'll try to address this in meetings, but may miss some folks.
=> Correct data source for gradebook grades

bulk_grades/__init__.py, bulk_grades/views.py
JIRA:PROD-553
**Description:** Rips out permissions which were there prospectively; we can add them all back in once discussions have landed about what rules should be applied. ~~For right now we don't expect an impact (nor traffic on them) since the corresponding UI elements will show only for Master's courses, of which there are none.~~ EDIT: there are masters courses, and those are the only ones broken in this way.
**JIRA:** https://openedx.atlassian.net/browse/PROD-553
**Reviewers:**
finished.
=> Remove permission checks which are preventing access to Gradebook

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py, tox.ini
https://openedx.atlassian.net/browse/EDUCATOR-4618
* Adds a Mixin class to help `GradesCSVProcessor` and `InterventionCSVProcessor` manage subsection column names in a sane way.
* Stops tox from running `pydocstyle`.
finished.
=> EDUCATOR-4618 | Prevent csv processor objects from having duplicate columns

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
**Description:** Pass a  `comment` to `grades_api.override_subsection_grade` when doing bulk grade upload, which will show up as 'Reason' in the override history view.
Also, add a user_id field to gradecsvprocessor to allow super_csv to track user if it loses the request context
**JIRA:** [EDUCATOR-4638](https://openedx.atlassian.net/browse/EDUCATOR-4638) 
**Reviewers:**
@edx/masters-devs 
finished.
=> EDUCATOR-4638 add comment to bulk grade upload

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/views.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt
The `GradeCSVProcessor.user_id` attribute was always null - we initiated the `_user` attribute instead.
Depends on https://github.com/edx/super-csv/pull/20
**JIRA:**
https://openedx.atlassian.net/browse/EDUCATOR-4638
finished.
=> EDUCATOR-4638 | Make sure GradeCSVProcessor.user_id is not null.

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
Accounts for the case where no `ScoreOverrider` records exists when fetching scores to add to a CSV.
**JIRA:**
https://openedx.atlassian.net/browse/EDUCATOR-4821
finished.
=> EDUCATOR-4821 | Account for cases where no score-overrider exists.

.travis.yml, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
Display student-key column for bulk export csv and populate it, it a student is in masters track.
[Jira](https://openedx.atlassian.net/browse/EDUCATOR-4928)
finished.
=> EDUCATOR-4928

bulk_grades/__init__.py, bulk_grades/api.py, mock_apps/student/models.py
**JIRA:**[ PROD-1352 ](https://openedx.atlassian.net/browse/PROD-1352)
Issue :
unable to download staff graded reports because there was recent change https://github.com/edx/edx-platform/blame/7f53a9ab9b4abfc550d3dc16e54cf63502330346/lms/djangoapps/program_enrollments/models.py#L110 so updated query and test accordingly to fix this issue.
finished.
=> Updated query according to model update

.travis.yml, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/clients.py, bulk_grades/models.py, bulk_grades/views.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, tox.ini
**Issue:** [BOM-1559](https://openedx.atlassian.net/browse/BOM-1559)
- Removed `python2.7` and added `python3.8`.
- Removed `django111`, `django20`, and `django21`.
- Updated constraints and made quality fixes.
=> Updated Python and Django versions in Travis and Tox

.annotation_safe_list.yml, CHANGELOG.rst, bulk_grades/__init__.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, test_settings.py
**Description:** Removes django-celery as that doesn't support celery 4.0+ versions
**JIRA:** https://openedx.atlassian.net/browse/BOM-2008
finished.
=> Remove django-celery

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/views.py, tests/test_api.py, tests/test_views.py
**Description:** We were including inactive learners in the bulk grades csv export. We don't want to do this.
**JIRA:** [EDUCATOR-5401](https://openedx.atlassian.net/browse/EDUCATOR-5401)
finished.
=> EDUCATOR-5401: CSV download includes inactive enrollments

CHANGELOG.rst, README.rst, bulk_grades/__init__.py
Updated the README file.
Build status badge is now pointing to 'travis-ci.com' instead of 'travis-ci.org'
JIRA: https://openedx.atlassian.net/browse/BOM-2089
=> Updated the build status badge to point to travis-ci.com

.travis.yml, CHANGELOG.rst, Makefile, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/clients.py, bulk_grades/views.py, manage.py, requirements/base.txt, requirements/celery44.txt, requirements/celery50.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pii_check.in, requirements/pii_check.txt, requirements/quality.txt, requirements/travis.txt, tests/test_api.py, tests/test_models.py, tests/test_views.py, tox.ini
**Description:** As we are planning to upgrade platform to latest version of `celery`, so we are going to add testing for the latest version of celery first.
- Added celery 5 support
- Moved `pii_check` requirements to new files as it was causing issues in testing multiple versions of celery
- Ran make upgrade
- Fixed quality
**JIRA:** https://openedx.atlassian.net/browse/BOM-2170
finished.
=> Added celery 5.0 for testing purpose

CHANGELOG.rst, Makefile, bulk_grades/__init__.py, requirements/base.txt, requirements/celery50.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pii_check.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, setup.py
**Description:**  
- Upgrade celery to 5.0.4
- Bumped Version
- Updated python classifier as python 3.5 is already dropped
finished.
=> Upgrade celery to 5.0.4

CHANGELOG.rst, Makefile, README.rst, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
added for easier integrations with some masters partners. if there is no override for a subsection, `grade-{subsection_id}` is the original grade. otherwise, it's the override grade.
I also added a install-local-bulk-grades make command to do the same thing as install-local-ora
**JIRA:** [EDUCATOR-4698](https://openedx.atlassian.net/browse/EDUCATOR-4698)
**Testing Instructions**:
- install-local-bulk-grades from bulk-grades dir
- make restart-lms from devstack dir
- go to a course and make some grades, go to localhost:1994/<course_id> (gradebook) and make some overrides
- navigate to localhost:18000/api/bulk_grades/course/<course_id> and your csv will download
- MAKE SURE PersistantCourseGradesFlag is enabled!!! http://localhost:18000/admin/grades/persistentgradesenabledflag/
**Merge …
=> EDUCATOR-4698: add assignment grade to bulk grade export

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
**Description:** Column filtering for bulk grade import history worked off the assumption that all subsections were present in the initial grade import. This assumption fails if subsections change or if an instructor trimmed down the original import and made it impossible to view historical reports. This adds a missing null check to handle these cases.
Also makes tests a bit DRYer.
**JIRA:** https://openedx.atlassian.net/browse/AU-5
finished.
=> Fix: pre-filtered columns breaking history report

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
It doesn't seem like original code intended for multiple grade override. With minimal change and minor refactor, it is able to do multiple update. It might be possible to wrap multiple override in a single update request. As for right now, it is sending request to `edx-platform/lms/djangoapps/grades/api.py::override_subsection_grade` for every subsection.
**Description:** 
**JIRA:**[AU-13](https://openedx.atlassian.net/browse/AU-13)
**Reproduce**: You can do this on stage/prod
- Have course that has more than 1 subsection
- Use `bulk management` to export the grades
- Modify grade on `new-override_{subsection-id}`
- Import grade using bulk management
- **You should see only one of the subsection's grade get override**
**Change**
- Follow the reproduce instruction
- **You should see all of …
=> fix: Gradebook Bulk Management not working with multiple per-user overrides

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, bulk_grades/views.py, tests/test_api.py
Fix bug where we ignore repeat user in the `csv import`. 
**Change**
- If the user show up more than once in the csv, the import will fail and send back the error message
- All of the error message now will show line number
**JIRA:** [AU-20](https://openedx.atlassian.net/browse/AU-20)
**Before**
**After**
finished.
=> fix: csv import should throw error on repeat user

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/views.py
**Description:** update csv error according discussed.
**JIRA:** [AU-66](https://openedx.atlassian.net/browse/AU-66)
Linked [PR](https://github.com/edx/frontend-app-gradebook/pull/205)
finished.
=> fix: update csv import error messages

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/api.py, tests/test_api.py
**Description:** Detect duplicate user_id on the first occurence.
**JIRA:** [AU-44](https://openedx.atlassian.net/browse/AU-44)
**Test instruction**
**Note**: duplicate error and other error are not mutually inclusive. As picture shown, line #2 appear to have different errors.
finished.
=> feat: row first row of error on duplicate user import

CHANGELOG.rst, bulk_grades/__init__.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pii_check.txt, requirements/quality.txt, requirements/test.txt
**Description:** 
Version bump to fix the history not rendering.
**JIRA:** [AU-115](https://openedx.atlassian.net/browse/AU-115)
**GitHub** [super-csv pr](https://github.com/edx/super-csv/pull/68)
finished.
=> version bump for super csv to fix history not rendering

Makefile, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt
Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions.
For reference, look at this https://github.com/openedx/edx-repo-health/pull/271 for new check added in edx-repo-health.
JIRA: https://2u-internal.atlassian.net/browse/BOM-3454
=> fix: Installed pip and pip-tools in upgrade script

CHANGELOG.rst, bulk_grades/__init__.py, bulk_grades/views.py, tests/test_views.py
**Description:** During investigation of a failed bulk grade upload, it was identified that the code to return error messaging actually had a bug, `line_numbers` was being referenced before it was being set. This cleans up that logic and removes that bug.
finished.
=> fix: fix issue with constructing an error message

requirements/ci.txt, requirements/dev.txt, requirements/doc.txt
In the previous PR for sphinx theme remvoal, somehow the compiled requirement
files still included edx-sphinx theme. This reruns the upgrade command to get
the package properly removed.
=> fix: rebuild requirements since edx-sphinx-theme wasn't removed

.github/workflows/ci.yml, CHANGELOG.rst, bulk_grades/__init__.py, requirements/base.txt, requirements/celery50.txt, requirements/celery53.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pii_check.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, setup.py, tox.ini
Added support for Django 4.2, to have more context on it please refer to the following [issue](https://github.com/edx/upgrades/issues/146)
=> fix: Added support for Django 4.2
